name: Merge me test dependencies!

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Run linters'
      - 'Run tests'
      - 'Test build package'

jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/shared-automerge.yml@67c2d834b83f6a05dd0d398d20d21b79f062d7fa # v5.2.2
    secrets:
      client_id: ${{ secrets.MERGE_APP_CLIENT_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
