name: Run benchmarks

on:
  workflow_call

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.10"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    # Service containers to run with `container-job`

    steps:
    - uses: actions/checkout@v5
    - uses: fizyk/actions-reuse/.github/actions/pipenv@v4.1.1
      with:
        python-version: ${{ matrix.python-version }}
        command: "pytest benchmarks/  --benchmark-json output.json"
        allow-prereleases: true
    - name: Analyse benchmark results for Pull Requests
      uses: benchmark-action/github-action-benchmark@v1.20.7
      if: ${{ github.ref != 'refs/heads/main' }}
      with:
        name: Matchbox performance benchmarks on Python ${{ matrix.python-version }}
        tool: 'pytest'
        output-file-path: output.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: false
        benchmark-data-dir-path: benchmarks
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@fizyk'
    - name: Store benchmark result for master branch
      uses: benchmark-action/github-action-benchmark@v1.20.7
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        name: Matchbox performance benchmarks on Python ${{ matrix.python-version }}
        tool: 'pytest'
        output-file-path: output.json
#        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
#        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        max-items-in-chart: 100
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        benchmark-data-dir-path: benchmarks
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@fizyk'
