name: Run benchmarks

on:
  workflow_call

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15", "pypy-3.11"]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    # Service containers to run with `container-job`

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: fizyk/actions-reuse/.github/actions/uv@42b61e053c1d70a61deb42b323c1a2229e2e7fe0 # v5.5.0
      with:
        python-version: ${{ matrix.python-version }}
        command: "pytest benchmarks/  --benchmark-json output.json"
    - name: Analyse benchmark results for Pull Requests
      uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1.22.1
      if: ${{ github.ref != 'refs/heads/main' }}
      with:
        name: Matchbox performance benchmarks on Python ${{ matrix.python-version }}
        tool: 'pytest'
        output-file-path: output.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: false
        benchmark-data-dir-path: benchmarks
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: false
        summary-always: true
        fail-on-alert: false
        alert-comment-cc-users: '@fizyk'
    - name: Store benchmark result for master branch
      uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1.22.1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        name: Matchbox performance benchmarks on Python ${{ matrix.python-version }}
        tool: 'pytest'
        output-file-path: output.json
#        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
#        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        max-items-in-chart: 100
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        benchmark-data-dir-path: benchmarks
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '200%'
        comment-on-alert: true
        fail-on-alert: false
        alert-comment-cc-users: '@fizyk'
