name: Test build package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    uses: fizyk/actions-reuse/.github/workflows/shared-pypi.yml@e434952f57d1da48b52d0fe5454b365b2f297d2d # v5.2.6
