name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to be added'
        required: true
        type: string

jobs:
  release:
    uses: fizyk/actions-reuse/.github/workflows/shared-release.yml@c76d10cf9448b3a9afdbef29e727e0fd00b2f544 # v5.2.8
    with:
      version: ${{ inputs.version }}
      dependency-manager: 'uv'
    secrets:
      app_id: ${{ secrets.RELEASE_APP_ID }}
      private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
